Repository wecode-bootcamp-korea/22-2nd-22percent-backend, pull requests merged in 2021-07, with the labels that each got.

#1 [22기 이동명] Add: set initial modeling
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  deals/__init__.py
  deals/admin.py
  deals/apps.py
  deals/migrations/0001_initial.py
  deals/migrations/__init__.py
  deals/models.py
  deals/tests.py
  deals/views.py
  investments/__init__.py
  investments/admin.py
  investments/apps.py
  investments/migrations/0001_initial.py
  investments/migrations/0002_initial.py
  investments/migrations/__init__.py
  investments/models.py
  investments/tests.py
  investments/views.py
  ttpercent/settings.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: 리뷰 요청

#2 Fix: Combine mortgages and selling_poings
  deals/migrations/0001_initial.py
  deals/models.py
  investments/migrations/0001_initial.py
  investments/migrations/0002_initial.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#4 Fix: set null for email
  users/models.py
Labels: Status: 리뷰 요청

#5 [22기 이동명 ] Add: user validator
  ttpercent/urls.py
  users/utils.py
Labels: Status: 수정 요청

#9 [22기 이동명] Add: Signup with email endpoint
  ttpercent/urls.py
  users/models.py
  users/tests.py
  users/urls.py
  users/utils.py
  users/views.py
Labels: Status: 리뷰 요청

#12 [22기 이동명] Add: Migration files
  users/migrations/0002_auto_20210722_1703.py
  users/utils.py
Labels: Status: 리뷰 요청

#6 [22기 이동명] Add: Email Signin endpoint
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: Accepted

#14 [22기 이동명] Fix: max length of deal statuses
  deals/migrations/0002_alter_dealstatus_name.py
  deals/models.py
  users/migrations/0002_auto_20210723_1125.py
Labels: Status: 리뷰 요청

#13 [22기 이동명] Add: Kakao Signup/Signin feature
  ttpercent/settings.py
  users/migrations/0002_auto_20210723_1125.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#17 [22기 이동명] Fix: Change models to use Enum
  deals/migrations/0001_initial.py
  deals/migrations/0002_alter_dealstatus_name.py
  deals/models.py
  investments/migrations/0001_initial.py
  investments/migrations/0002_initial.py
  investments/models.py
  users/migrations/0001_initial.py
  users/migrations/0002_auto_20210722_1703.py
Labels: Status: 리뷰 요청

#18 [22기 이동명] Fix: change label from english to korean
  deals/migrations/0001_initial.py
  deals/models.py
  investments/migrations/0001_initial.py
  investments/migrations/0002_initial.py
  investments/models.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#19 [22기 이동명] Fix: Move Regex Validator to Model
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: 리뷰 요청

#23 [22기 이동명] Fix: change to setUptestData from setUp/tearDown
  users/tests.py
Labels: Status: 리뷰 요청

#16 [22기 전수현]add detailview
  deals/models.py
  deals/tests.py
  deals/urls.py
  deals/views.py
  ttpercent/urls.py
Labels: Status: 리뷰 요청

#22 [22기 이동명] 모델링 수정 add: scheduled value for deal
  deals/migrations/0001_initial.py
  deals/models.py
  investments/migrations/0001_initial.py
  investments/migrations/0002_initial.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#24 [22기 이준영] 마이페이지 투자내역 리스트 구현
  deals/urls.py
  investments/tests.py
  investments/urls.py
  investments/views.py
  ttpercent/urls.py
Labels: Status: 리뷰 요청

#26 [22기 이동명] 모델링 수정Add: interest attribute in deal model
  deals/migrations/0001_initial.py
  deals/models.py
  investments/migrations/0001_initial.py
  investments/migrations/0002_initial.py
  users/migrations/0001_initial.py
Labels: Status: Accepted

#15 [22기 이준영] Deal list 구현
  deals/tests.py
  deals/urls.py
  deals/views.py
Labels: Status: Accepted

#27 [22기 이동명] 모델링 수정 Add: Option Enum in PaybackSchedule Model
  deals/migrations/0001_initial.py
  investments/migrations/0001_initial.py
  investments/migrations/0002_auto_20210727_1652.py
  investments/models.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#28 [22기 이동명] 모델링 수정Feature/modeling
  deals/migrations/0001_initial.py
  investments/migrations/0001_initial.py
  investments/migrations/0002_auto_20210727_2129.py
  investments/models.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#29 [22기 이동명] 모델링 수정 Add: Invest Deal feature
  deals/migrations/0001_initial.py
  investments/migrations/0001_initial.py
  investments/migrations/0002_auto_20210727_2149.py
  investments/models.py
  investments/tests.py
  investments/urls.py
  investments/views.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#21 [22기 이동명] Add: 마이페이지 투자요약 포트폴리오 엔드포인트
  investments/tests.py
  investments/urls.py
  investments/utils.py
  investments/views.py
  ttpercent/urls.py
Labels: Status: 컨플릭트 해결 요청

#20 [22기 이동명] Add: investment summary endpoint
  investments/tests.py
  investments/urls.py
  investments/views.py
  users/utils.py
Labels: Status: Accepted

#31 [22기 이동명] 모델링 수정 Fix: database name
  deals/migrations/0001_initial.py
  investments/migrations/0001_initial.py
  investments/migrations/0002_initial.py
  investments/models.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#25 [22기 이준영] 마이페이지 투자내역 xlsx파일 export 구현
  investments/tests.py
  investments/urls.py
  investments/views.py
  requirements.txt
  ttpercent/urls.py
Labels: Status: 리뷰 요청

#32 [22기 이준영] Fix: 모델링 변경에 따른 상품 리스트 로직 수정
  deals/tests.py
  deals/views.py
Labels: Status: 리뷰 요청

#33 [22기 이준영] 메인페이지 누적 대출액 구현
  deals/tests.py
  deals/urls.py
  deals/views.py
Labels: Status: Accepted

#30 [22기 이동명] Add: 상품투자하기 엔드포인트
  investments/tests.py
  investments/urls.py
  investments/views.py
Labels: Status: 리뷰 요청

#34 [22기 이동명] Add: public login
  users/utils.py
Labels: Status: 리뷰 요청

#35 [22기 전수현] dealdetailview 수정
  deals/tests.py
  deals/views.py
Labels: Status: 수정 요청

#36 [22기 이준영] 상품 투자여부 상품 리스트에 표시
  deals/tests.py
  deals/views.py
Labels: Status: 리뷰 요청

#39 [22기 이동명] requirements 수정Add: requirements
  .gitignore
  requirements.txt
  ttpercent/settings.py
Labels: Status: 리뷰 요청

#38 [22기 전수현]Feature/detailinvestview
  deals/urls.py
  deals/views.py
  investments/models.py
Labels: Status: 리뷰 요청

#40 [22기 이동명] 투자하기 Fix: Error Handle
  investments/views.py
Labels: Status: 리뷰 요청

#37 [22기 전수현]Feature/invest
  deals/models.py
  deals/tests.py
  deals/views.py
  investments/urls.py
  investments/views.py
  users/views.py
Labels: Status: 리뷰 요청
